language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:

before_script:
  - composer install --dev
  - cat vendor/autoload.php

script:
  - phpunit tests --bootstrap=vendor/autoload.php --coverage-text

after_script: