language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:

before_script:
  - composer install --dev
  - cat vendor/autoload.php

script:
  - vendor/bin/phpunit --bootstrap=vendor/autoload.php tests

after_script:
